version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kingpadel_postgres
    environment:
      POSTGRES_USER: kingpadel
      POSTGRES_PASSWORD: kingpadel
      POSTGRES_DB: kingpadel_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kingpadel']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kingpadel_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: kingpadel_maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  postgres_data:
  redis_data:
